/* 
 * Maui, Maltcms User Interface. 
 * Copyright (C) 2008-2014, The authors of Maui. All rights reserved.
 *
 * Project website: http://maltcms.sf.net
 *
 * Maui may be used under the terms of either the
 *
 * GNU Lesser General Public License (LGPL)
 * http://www.gnu.org/licenses/lgpl.html
 *
 * or the
 *
 * Eclipse Public License (EPL)
 * http://www.eclipse.org/org/documents/epl-v10.php
 *
 * As a user/recipient of Maui, you may choose which license to receive the code 
 * under. Certain files or entire directories may not be covered by this 
 * dual license, but are subject to licenses compatible to both LGPL and EPL.
 * License exceptions are explicitly declared in all relevant files or in a 
 * LICENSE file in the relevant directories.
 *
 * Maui is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. Please consult the relevant license documentation
 * for details.
 */
package net.sf.maltcms.chromaui.rserve.options;

import java.io.File;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import net.sf.maltcms.chromaui.rserve.api.RserveConnectionFactory;
import org.netbeans.api.keyring.Keyring;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.filesystems.FileChooserBuilder.SelectionApprover;
import org.openide.util.Exceptions;
import org.openide.util.NbPreferences;
import org.openide.util.RequestProcessor;
import org.openide.util.RequestProcessor.Task;
import org.openide.util.TaskListener;
import org.rosuda.REngine.REXP;
import org.rosuda.REngine.REXPMismatchException;
import org.rosuda.REngine.Rserve.RConnection;
import org.rosuda.REngine.Rserve.RserveException;

final class RServePanel extends javax.swing.JPanel {

    private final RServeOptionsPanelController controller;

    RServePanel(RServeOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localRserveSettingsField = new javax.swing.JTextField();
        localRserverArgsLabel = new javax.swing.JLabel();
        useLocalInstance = new javax.swing.JCheckBox();
        remoteHostIpField = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        remoteHostLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        remoteHostPortField = new javax.swing.JTextField();
        remoteHostPortLabel = new javax.swing.JLabel();
        debugMode = new javax.swing.JCheckBox();
        rscriptLocation = new javax.swing.JTextField();
        rBinaryLocation = new javax.swing.JTextField();
        rScriptLocationLabel = new javax.swing.JLabel();
        rBinaryLocationLabel = new javax.swing.JLabel();
        rbinaryLocationButton = new javax.swing.JButton();
        rscriptLocationButton = new javax.swing.JButton();
        autodetectButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        localRserveSettingsField.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.localRserveSettingsField.text")); // NOI18N
        localRserveSettingsField.setToolTipText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.localRserveSettingsField.toolTipText")); // NOI18N
        localRserveSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localRserveSettingsFieldActionPerformed(evt);
            }
        });

        localRserverArgsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(localRserverArgsLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.localRserverArgsLabel.text")); // NOI18N

        useLocalInstance.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(useLocalInstance, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.useLocalInstance.text")); // NOI18N
        useLocalInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useLocalInstanceActionPerformed(evt);
            }
        });

        remoteHostIpField.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.remoteHostIpField.text")); // NOI18N
        remoteHostIpField.setEnabled(false);

        userNameField.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.userNameField.text")); // NOI18N
        userNameField.setEnabled(false);
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        passwordField.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.passwordField.text")); // NOI18N
        passwordField.setEnabled(false);

        remoteHostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(remoteHostLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.remoteHostLabel.text")); // NOI18N

        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(userNameLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.userNameLabel.text")); // NOI18N

        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.passwordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(testButton, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.testButton.text")); // NOI18N
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        remoteHostPortField.setColumns(5);
        remoteHostPortField.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.remoteHostPortField.text")); // NOI18N
        remoteHostPortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoteHostPortFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(remoteHostPortLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.remoteHostPortLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(debugMode, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.debugMode.text")); // NOI18N
        debugMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugModeActionPerformed(evt);
            }
        });

        rscriptLocation.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rscriptLocation.text")); // NOI18N

        rBinaryLocation.setText(org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rBinaryLocation.text")); // NOI18N

        rScriptLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(rScriptLocationLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rScriptLocationLabel.text")); // NOI18N

        rBinaryLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(rBinaryLocationLabel, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rBinaryLocationLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rbinaryLocationButton, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rbinaryLocationButton.text")); // NOI18N
        rbinaryLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbinaryLocationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(rscriptLocationButton, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.rscriptLocationButton.text")); // NOI18N
        rscriptLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rscriptLocationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(autodetectButton, org.openide.util.NbBundle.getMessage(RServePanel.class, "RServePanel.autodetectButton.text")); // NOI18N
        autodetectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autodetectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBinaryLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rScriptLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rscriptLocation)
                            .addComponent(rBinaryLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbinaryLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rscriptLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 343, Short.MAX_VALUE)
                        .addComponent(useLocalInstance))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remoteHostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localRserverArgsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordField)
                                    .addComponent(userNameField)
                                    .addComponent(localRserveSettingsField))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(remoteHostPortLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(remoteHostPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(debugMode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remoteHostIpField)
                                .addGap(138, 138, 138))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(autodetectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbinaryLocationButton, rscriptLocationButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {localRserverArgsLabel, passwordLabel, rBinaryLocationLabel, rScriptLocationLabel, remoteHostLabel, userNameLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBinaryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBinaryLocationLabel)
                    .addComponent(rbinaryLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rscriptLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rScriptLocationLabel)
                    .addComponent(rscriptLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autodetectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useLocalInstance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localRserveSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localRserverArgsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remoteHostIpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remoteHostLabel)
                    .addComponent(remoteHostPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remoteHostPortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testButton)
                    .addComponent(debugMode))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void localRserveSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localRserveSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localRserveSettingsFieldActionPerformed

    private void useLocalInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useLocalInstanceActionPerformed
        updateUseLocalInstance();
    }//GEN-LAST:event_useLocalInstanceActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    public boolean testRserve() {
        try {
            RConnection connection = RserveConnectionFactory.getDefaultConnection();
            REXP rexp = connection.eval("x <- seq(from=1,by=1,to=10);");
            try {
                Logger.getLogger(getClass().getName()).log(Level.INFO, "Result: {0}", Arrays.toString(rexp.asDoubles()));
                return true;
            } catch (REXPMismatchException ex) {
                ex.printStackTrace();
            }
        } catch (RserveException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        Runnable r = new Runnable() {
            @Override
            public void run() {
                testButton.setEnabled(false);
                try {
                    if (useLocalInstance.isSelected()) {
                        store();
                        if (testRserve()) {
                            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message("Connection to Rserve successful!", NotifyDescriptor.INFORMATION_MESSAGE));
                        } else {
                            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message("Connection to Rserve failed!", NotifyDescriptor.ERROR_MESSAGE));
                        }
                    } else {
                        try {
                            InetAddress address = InetAddress.getByName(remoteHostIpField.getText().trim());
                            int port = Integer.parseInt(remoteHostPortField.getText().trim());
                            store();
                            if (testRserve()) {
                                DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message("Connection to Rserve successful!", NotifyDescriptor.INFORMATION_MESSAGE));
                            } else {
                                DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message("Connection to Rserve failed!", NotifyDescriptor.ERROR_MESSAGE));
                            }
                        } catch (UnknownHostException ex) {
                            Exceptions.printStackTrace(ex);
                        }

                    }
                } finally {
                    testButton.setEnabled(true);
                }
            }
        };
        RequestProcessor rp = new RequestProcessor("Rserve connection test thread pool", 1, false);
        Task t = rp.create(r);
        final ProgressHandle ph = ProgressHandleFactory.createHandle("Rserve connection test", t);
        t.addTaskListener(new TaskListener() {
            @Override
            public void taskFinished(org.openide.util.Task task) {
                //make sure that we get rid of the ProgressHandle
                //when the task is finished
                ph.finish();
            }
        });
        ph.start();
        t.schedule(0);
    }//GEN-LAST:event_testButtonActionPerformed

    private void remoteHostPortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteHostPortFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remoteHostPortFieldActionPerformed

    private void debugModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debugModeActionPerformed

    private void rbinaryLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbinaryLocationButtonActionPerformed
        FileChooserBuilder fcb = new FileChooserBuilder(RServePanel.class);
        File basedir = new File(System.getProperty("user.home"));
        if(!rBinaryLocation.getText().isEmpty()) {
            basedir = new File(rBinaryLocation.getText()).getParentFile();
        }
        File file = fcb.setDefaultWorkingDirectory(basedir).setFilesOnly(true).setControlButtonsAreShown(true).setApproveText("Select").setTitle("Select R executable").showOpenDialog();
        if(file!=null && file.isFile()) {
            rBinaryLocation.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_rbinaryLocationButtonActionPerformed

    private void rscriptLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rscriptLocationButtonActionPerformed
        FileChooserBuilder fcb = new FileChooserBuilder(RServePanel.class);
        File basedir = new File(System.getProperty("user.home"));
        if(!rscriptLocation.getText().isEmpty()) {
            basedir = new File(rscriptLocation.getText()).getParentFile();
        }
        File file = fcb.setDefaultWorkingDirectory(basedir).setFilesOnly(true).setControlButtonsAreShown(true).setApproveText("Select").setTitle("Select Rscript executable").showOpenDialog();
        if(file!=null && file.isFile()) {
            rscriptLocation.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_rscriptLocationButtonActionPerformed

    private void autodetectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autodetectButtonActionPerformed
        File rBinaryLocationFile = RserveConnectionFactory.getInstance().getRBinaryLocation();
        if (rBinaryLocationFile != null) {
            rBinaryLocation.setText(rBinaryLocationFile.getAbsolutePath());
        }
        File rScriptLocationFile = RserveConnectionFactory.getInstance().getRscriptLocation();
        if (rScriptLocationFile != null) {
            rscriptLocation.setText(rScriptLocationFile.getAbsolutePath());
        }
    }//GEN-LAST:event_autodetectButtonActionPerformed

    private void updateUseLocalInstance() {
        if (useLocalInstance.isSelected()) {
            localRserveSettingsField.setEnabled(true);
            remoteHostIpField.setEnabled(false);
            remoteHostPortField.setEnabled(false);
            userNameField.setEnabled(false);
            passwordField.setEnabled(false);
        } else {
            localRserveSettingsField.setEnabled(false);
            remoteHostIpField.setEnabled(true);
            remoteHostPortField.setEnabled(true);
            userNameField.setEnabled(true);
            passwordField.setEnabled(true);
        }
    }

    void load() {
        localRserveSettingsField.setText(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVEARGS, ""));
        File rbinaryLocation = RserveConnectionFactory.getInstance().getRBinaryLocation();
        if (rbinaryLocation != null) {
            rBinaryLocation.setText(rbinaryLocation.getAbsolutePath());
        }
        File rscriptLocationFile = RserveConnectionFactory.getInstance().getRscriptLocation();
        if (rscriptLocationFile != null) {
            rscriptLocation.setText(rscriptLocationFile.getAbsolutePath());
        }
        remoteHostIpField.setText(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVE_HOST, "127.0.0.1"));
        remoteHostPortField.setText(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVE_PORT, "6311"));
        userNameField.setText(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVE_USER, ""));
        useLocalInstance.setSelected(Boolean.parseBoolean(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVE_LOCAL, "true")));
        debugMode.setSelected(Boolean.parseBoolean(NbPreferences.forModule(RserveConnectionFactory.class).get(RserveConnectionFactory.KEY_RSERVE_DEBUG, "false")));
        char[] password = Keyring.read("Rserve://" + remoteHostIpField.getText().trim());
        if (password != null) {
            passwordField.setText(String.valueOf(password));
        }
        updateUseLocalInstance();
    }

    void store() {
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVE_LOCAL, useLocalInstance.isSelected() + "");
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVEARGS, localRserveSettingsField.getText());
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVE_HOST, remoteHostIpField.getText());
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVE_PORT, remoteHostPortField.getText());
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVE_USER, userNameField.getText());
        String rbinaryLocationFile = rBinaryLocation.getText();
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RBINARY_LOCATION, rbinaryLocationFile == null ? "" : rbinaryLocationFile);
        String rscriptLocationFile = rscriptLocation.getText();
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSCRIPT_LOCATION, rscriptLocationFile == null ? "" : rscriptLocationFile);
        if (!remoteHostIpField.getText().isEmpty()) {
            Keyring.save("Rserve://" + remoteHostIpField.getText().trim(), passwordField.getPassword(), "Rserve password for host " + remoteHostIpField.getText());
        }
        NbPreferences.forModule(RserveConnectionFactory.class).put(RserveConnectionFactory.KEY_RSERVE_DEBUG, debugMode.isSelected() + "");
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autodetectButton;
    private javax.swing.JCheckBox debugMode;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField localRserveSettingsField;
    private javax.swing.JLabel localRserverArgsLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField rBinaryLocation;
    private javax.swing.JLabel rBinaryLocationLabel;
    private javax.swing.JLabel rScriptLocationLabel;
    private javax.swing.JButton rbinaryLocationButton;
    private javax.swing.JTextField remoteHostIpField;
    private javax.swing.JLabel remoteHostLabel;
    private javax.swing.JTextField remoteHostPortField;
    private javax.swing.JLabel remoteHostPortLabel;
    private javax.swing.JTextField rscriptLocation;
    private javax.swing.JButton rscriptLocationButton;
    private javax.swing.JButton testButton;
    private javax.swing.JCheckBox useLocalInstance;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
