/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maltcms.ui.fileHandles.properties;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.logging.Logger;
import javax.swing.JComponent;
import maltcms.ui.fileHandles.properties.graph.PipelineGraphScene;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.api.visual.layout.SceneLayout;
import org.netbeans.api.visual.widget.Widget;
import org.openide.util.ImageUtilities;
import org.openide.windows.CloneableTopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//de.chromA.pipelineEditor//PipelineEditor//EN",
autostore = false)
public final class PipelineEditorTopComponent extends CloneableTopComponent {

    private static PipelineEditorTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "PipelineEditorTopComponent";
    private SceneLayout layout;
    private PipelineGraphScene scene;
    protected JComponent view;
    private double zoomSteps = 0.2d;

    public PipelineEditorTopComponent() {
        this.scene = new PipelineGraphScene();
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
        this.view = this.scene.createView();

        initComponents();

        layout = new SceneLayout(this.scene) {

            @Override
            protected void performLayout() {
                if (scene.getChildren().size() > 0) {
                    Rectangle rectangle = new Rectangle(0, 0, 1, 1);
                    for (Widget widget : scene.getChildren()) {
                        rectangle = rectangle.union(widget.convertLocalToScene(widget.getBounds()));
                    }
                    Dimension dim = rectangle.getSize();
                    Dimension viewDim = jScrollPane1.getViewportBorderBounds().getSize();
                    scene.setZoomFactor(Math.min((float) viewDim.width / dim.width, (float) viewDim.height / dim.height));
                }
            }
        };
        this.scene.setLayout(layout);

        //add(this.view, java.awt.BorderLayout.CENTER);

        setName(NbBundle.getMessage(PipelineEditorTopComponent.class, "CTL_PipelineEditorTopComponent"));
        setToolTipText(NbBundle.getMessage(PipelineEditorTopComponent.class, "HINT_PipelineEditorTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
    }

    public void setPipelineGraphScene(PipelineGraphScene scene) {
        this.scene = scene;
    }

    public PipelineGraphScene getPipelineGraphScene() {
        return this.scene;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        GridsToggleButton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane(this.view);

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);

        GridsToggleButton.setIcon(ImageUtilities.image2Icon(ImageUtilities.loadImage("maltcms/ui/fileHandles/properties/resources/dots.gif")));
        GridsToggleButton.setSelected(true);
        GridsToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GridsToggleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(GridsToggleButton);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(PipelineEditorTopComponent.class, "PipelineEditorTopComponent.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(PipelineEditorTopComponent.class, "PipelineEditorTopComponent.jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(PipelineEditorTopComponent.class, "PipelineEditorTopComponent.jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        add(jToolBar1, java.awt.BorderLayout.NORTH);
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void GridsToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GridsToggleButtonActionPerformed
        if (GridsToggleButton.isSelected()) {
            this.scene.initGrids();
        } else {
            this.scene.setBackground(Color.WHITE);
            this.scene.validate();
        }
}//GEN-LAST:event_GridsToggleButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double cz = this.scene.getZoomFactor();
        if (cz - this.zoomSteps > 0) {
            this.scene.setZoomFactor(this.scene.getZoomFactor() - this.zoomSteps);
            this.scene.validate();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double cz = this.scene.getZoomFactor();
        if (cz + this.zoomSteps < 5) {
            this.scene.setZoomFactor(this.scene.getZoomFactor() + this.zoomSteps);
            this.scene.validate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.layout.invokeLayout();
        this.scene.validate();
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GridsToggleButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized PipelineEditorTopComponent getDefault() {
        if (instance == null) {
            instance = new PipelineEditorTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the PipelineEditorTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized PipelineEditorTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(PipelineEditorTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof PipelineEditorTopComponent) {
            return (PipelineEditorTopComponent) win;
        }
        Logger.getLogger(PipelineEditorTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
