/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.maltcms.chromaui.statistics.pcaViewer;

import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import de.unibielefeld.cebitec.lstutz.pca.visual.StandardGUI;
import java.awt.BorderLayout;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
dtd = "-//net.sf.maltcms.chromaui.statistics.pcaViewer//PCAViewer//EN",
autostore = false)
@TopComponent.Description(preferredID = "PCAViewerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window",
id = "net.sf.maltcms.chromaui.statistics.pcaViewer.PCAViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_PCAViewerAction",
preferredID = "PCAViewerTopComponent")
public final class PCAViewerTopComponent extends TopComponent {

    private StandardGUI scene = null;
    
    public PCAViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(PCAViewerTopComponent.class,
                "CTL_PCAViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(PCAViewerTopComponent.class,
                "HINT_PCAViewerTopComponent"));
    }
    
    public void setData(StandardGUI sg) {
        if(scene==null) {
            add(sg,BorderLayout.CENTER);
        }else{
            throw new IllegalStateException("StandardGUI may only be added once!");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
