/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MassSpectrumPanel.java
 *
 * Created on 15.05.2010, 16:13:36
 */
package maltcms.ui.viewer.gui;

import cross.Factory;
import cross.datastructures.fragments.CachedList;
import cross.datastructures.fragments.VariableFragment;
import java.awt.Point;
import maltcms.ui.viewer.InformationController;
import maltcms.ui.viewer.tools.ChromatogramVisualizerTools;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.xy.XYBarDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author mwilhelm
 */
public class MassSpectrumPanel extends PanelE {

    private InformationController ic;
    private XYSeriesCollection sc;

    /** Creates new form MassSpectrumPanel */
    public MassSpectrumPanel(InformationController ic) {
        this.ic = ic;
        initComponents();
        initChartComponents();
    }

    private void initChartComponents() {

        this.sc = new XYSeriesCollection();
        XYSeries s = new XYSeries("asd");
        s.add(1, 1);
        this.sc.addSeries(s);
        XYBarDataset d = new XYBarDataset(sc, 0.5d);
        XYBarRenderer renderer = new XYBarRenderer(0.1d);
        XYPlot p = new XYPlot(d, new NumberAxis("mz"), new NumberAxis("intensity"), renderer);
        JFreeChart msChart = new JFreeChart(p);

        Factory.getInstance().getConfiguration().setProperty(VariableFragment.class.getName()
                + ".useCachedList", false);
        Factory.getInstance().getConfiguration().setProperty(CachedList.class.getName()
                + ".cacheSize", 1024);
        Factory.getInstance().getConfiguration().setProperty(CachedList.class.getName()
                + ".prefetchOnMiss", true);
        System.out.println("Creating ms chart 3");

        this.cp = new ChartPanel(msChart);
        this.cp.getChart().getLegend().setVisible(true);
        this.jButton1ActionPerformed(null);
        this.jPanel2.removeAll();
        this.jPanel2.add(this.cp);
        this.jPanel2.repaint();
    }

    public void changeMS(Point imagePoint) {
        XYSeries s = ChromatogramVisualizerTools.getMSSeries(imagePoint, this.ic.getFilename());

        if (this.jToggleButton1.isSelected()) {
            this.sc.addSeries(s);
        } else {
            this.sc = new XYSeriesCollection();
            this.sc.addSeries(s);
            this.cp.repaint();
            ((XYPlot) this.cp.getChart().getPlot()).setDataset(sc);
        }
//        this.cp.getChart().getPlot().datasetChanged(new DatasetChangeEvent(this, this.sc));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("maltcms/ui/viewer/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("MassSpectrumPanel.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jToggleButton1.setText(bundle.getString("MassSpectrumPanel.jToggleButton1.text")); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.sc.removeAllSeries();
        this.cp.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
