/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Viewer2Panel.java
 *
 * Created on 22.05.2010, 14:05:08
 */
package maltcms.ui.viewer.gui;

import maltcms.ui.viewer.InformationController;

/**
 *
 * @author mw
 */
public class Viewer2Panel extends javax.swing.JPanel {

    private InformationController ic;

    /** Creates new form Viewer2Panel */
    public Viewer2Panel(InformationController ic) {
        this.ic = ic;
        initComponents();
        this.middleSplitPane.setDividerLocation(600);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middleSplitPane = new javax.swing.JSplitPane();
        westPanel = this.ic.getHMP();
        eastPanel = this.ic.getAIP2();

        middleSplitPane.setDividerSize(5);

        westPanel.setLayout(new java.awt.GridLayout(1, 0));
        middleSplitPane.setLeftComponent(westPanel);

        eastPanel.setLayout(new java.awt.GridLayout(1, 0));
        middleSplitPane.setRightComponent(eastPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(middleSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(middleSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eastPanel;
    private javax.swing.JSplitPane middleSplitPane;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

}
