/* 
 * Maui, Maltcms User Interface. 
 * Copyright (C) 2008-2012, The authors of Maui. All rights reserved.
 *
 * Project website: http://maltcms.sf.net
 *
 * Maui may be used under the terms of either the
 *
 * GNU Lesser General Public License (LGPL)
 * http://www.gnu.org/licenses/lgpl.html
 *
 * or the
 *
 * Eclipse Public License (EPL)
 * http://www.eclipse.org/org/documents/epl-v10.php
 *
 * As a user/recipient of Maui, you may choose which license to receive the code 
 * under. Certain files or entire directories may not be covered by this 
 * dual license, but are subject to licenses compatible to both LGPL and EPL.
 * License exceptions are explicitly declared in all relevant files or in a 
 * LICENSE file in the relevant directories.
 *
 * Maui is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. Please consult the relevant license documentation
 * for details.
 */
package maltcms.ui.viewer.gui;

import javax.swing.JPanel;
import maltcms.ui.viewer.InformationController;
//import org.openide.util.ImageUtilities;

/**
 * Top component which displays something.
 */
public final class Viewer4Panel extends JPanel {

    private InformationController ic;

    public Viewer4Panel(InformationController ic) {
        this.ic = ic;
        initComponents();
        this.middleSplitPane.setDividerLocation(600);
        this.leftSplitPane.setDividerLocation(150);
    }

    public void initCharts() {
        this.leftSplitPane.setLeftComponent(new AdditionalInformationPanel(this.ic, ChartPositions.NorthWest));
        this.rightSplitPane.setLeftComponent(new MassSpectrumPanel(ic));
        this.leftSplitPane.setRightComponent(new HeatMapPanel(ic));
        this.rightSplitPane.setRightComponent(new AdditionalInformationPanel(this.ic, ChartPositions.SouthEast));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        middleSplitPane = new javax.swing.JSplitPane();
        leftSplitPane = new javax.swing.JSplitPane();
        northWestPanel = this.ic.getAIP1();
        southWestPanel = this.ic.getHMP();
        rightSplitPane = new javax.swing.JSplitPane();
        northEastPanel = this.ic.getMSP();
        southEastPanel = this.ic.getAIP2();

        middleSplitPane.setDividerLocation(200);
        middleSplitPane.setDividerSize(5);

        leftSplitPane.setDividerSize(5);
        leftSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rightSplitPane, org.jdesktop.beansbinding.ELProperty.create("${dividerLocation}"), leftSplitPane, org.jdesktop.beansbinding.BeanProperty.create("dividerLocation"));
        bindingGroup.addBinding(binding);

        northWestPanel.setLayout(new java.awt.GridLayout(1, 0));
        leftSplitPane.setTopComponent(northWestPanel);

        southWestPanel.setLayout(new java.awt.GridLayout(1, 0));
        leftSplitPane.setRightComponent(southWestPanel);

        middleSplitPane.setLeftComponent(leftSplitPane);

        rightSplitPane.setDividerSize(5);
        rightSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        northEastPanel.setLayout(new java.awt.GridLayout(1, 0));
        rightSplitPane.setTopComponent(northEastPanel);

        southEastPanel.setLayout(new java.awt.GridLayout(1, 0));
        rightSplitPane.setRightComponent(southEastPanel);

        middleSplitPane.setRightComponent(rightSplitPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(middleSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(middleSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane leftSplitPane;
    private javax.swing.JSplitPane middleSplitPane;
    private javax.swing.JPanel northEastPanel;
    private javax.swing.JPanel northWestPanel;
    private javax.swing.JSplitPane rightSplitPane;
    private javax.swing.JPanel southEastPanel;
    private javax.swing.JPanel southWestPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
