/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.maltcms.chromaui.project.spi.ui;

/**
 *
 * @author hoffmann
 */
public class PeakMatchSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PeakMatchSelectionPanel
     */
    public PeakMatchSelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        startsWith = new javax.swing.JRadioButton();
        endsWith = new javax.swing.JRadioButton();
        matches = new javax.swing.JRadioButton();
        contains = new javax.swing.JRadioButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.jTextField1.text")); // NOI18N

        buttonGroup1.add(startsWith);
        startsWith.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.startsWith.text")); // NOI18N
        startsWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startsWithActionPerformed(evt);
            }
        });

        buttonGroup1.add(endsWith);
        endsWith.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.endsWith.text")); // NOI18N

        buttonGroup1.add(matches);
        matches.setSelected(true);
        matches.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.matches.text")); // NOI18N

        buttonGroup1.add(contains);
        contains.setText(org.openide.util.NbBundle.getMessage(PeakMatchSelectionPanel.class, "PeakMatchSelectionPanel.contains.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startsWith)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endsWith)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contains)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matches))
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startsWith)
                    .addComponent(endsWith)
                    .addComponent(matches)
                    .addComponent(contains))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startsWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startsWithActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startsWithActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton contains;
    private javax.swing.JRadioButton endsWith;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton matches;
    private javax.swing.JRadioButton startsWith;
    // End of variables declaration//GEN-END:variables
}
