/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataSourcePanel.java
 *
 * Created on 23.11.2011, 21:13:04
 */
package maltcms.ui.nb.pipelineRunner.ui;

import java.io.File;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import net.sf.maltcms.chromaui.project.api.descriptors.IPeakGroupDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 * TODO a panel to select the peak used for normalization (by name)
 * and the external normalization method (e.g. via the normalizationDesriptor)
 * @author nilshoffmann
 */
public class DataSourcePanel extends javax.swing.JPanel {

    /** Creates new form DataSourcePanel */
    public DataSourcePanel() {
        initComponents();
    }
    public static final String ORIGINAL_FILES = "Original Project Files"; 
    public static final String IMPORTED_FILES = "Import Directory Files";

    public DataSourcePanel(FileObject projectBasedir) {
        List<String> model = new LinkedList<String>();
        model.add("Original Project Files");
        File importDir = new File(FileUtil.toFile(
                projectBasedir), "import");
        if (importDir.exists() && importDir.isDirectory()) {
            model.add("Import Directory Files");
        }
        initComponents();
        dataSourceComboBox.setModel(new DefaultComboBoxModel(model.toArray(new String[model.size()])));
    }
    
    public String getSelectedDataSource() {
        return (String)dataSourceComboBox.getSelectedItem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataSourceComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        dataSourceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Original Project Files", "Import Directory Files" }));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DataSourcePanel.class, "DataSourcePanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataSourceComboBox, 0, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dataSourceComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
