/* 
 * Maui, Maltcms User Interface. 
 * Copyright (C) 2008-2014, The authors of Maui. All rights reserved.
 *
 * Project website: http://maltcms.sf.net
 *
 * Maui may be used under the terms of either the
 *
 * GNU Lesser General Public License (LGPL)
 * http://www.gnu.org/licenses/lgpl.html
 *
 * or the
 *
 * Eclipse Public License (EPL)
 * http://www.eclipse.org/org/documents/epl-v10.php
 *
 * As a user/recipient of Maui, you may choose which license to receive the code 
 * under. Certain files or entire directories may not be covered by this 
 * dual license, but are subject to licenses compatible to both LGPL and EPL.
 * License exceptions are explicitly declared in all relevant files or in a 
 * LICENSE file in the relevant directories.
 *
 * Maui is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. Please consult the relevant license documentation
 * for details.
 */
package maltcms.ui.nb.pipelineRunner.ui;

import java.io.File;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import net.sf.maltcms.chromaui.project.api.descriptors.IPeakGroupDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 * TODO a panel to select the peak used for normalization (by name) and the
 * external normalization method (e.g. via the normalizationDesriptor)
 *
 * @author nilshoffmann
 */
public class DataSourcePanel extends javax.swing.JPanel {

    /**
     * Creates new form DataSourcePanel
     */
    public DataSourcePanel() {
        initComponents();
    }
    public static final String ORIGINAL_FILES = "Original Project Files";
    public static final String IMPORTED_FILES = "Import Directory Files";
    public static final String MALTCMS_FILES = "Maltcms Result Files";

    public DataSourcePanel(FileObject projectBasedir) {
        List<String> model = new LinkedList<>();
        model.add(ORIGINAL_FILES);
        File importDir = new File(FileUtil.toFile(
                projectBasedir), "import");
        if (importDir.exists() && importDir.isDirectory()) {
            model.add(IMPORTED_FILES);
        }
        File maltcmsDir = new File(FileUtil.toFile(projectBasedir), "output");
        if (maltcmsDir.exists() && maltcmsDir.isDirectory()) {
            model.add(MALTCMS_FILES);
        }
        initComponents();
        dataSourceComboBox.setModel(new DefaultComboBoxModel(model.toArray(new String[model.size()])));
    }

    public String getSelectedDataSource() {
        return (String) dataSourceComboBox.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataSourceComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        dataSourceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Original Project Files", "Import Directory Files", "Maltcms Result Files" }));
        dataSourceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSourceComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DataSourcePanel.class, "DataSourcePanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataSourceComboBox, 0, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataSourceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSourceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSourceComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dataSourceComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
