/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.maltcms.chromaui.msviewer.api.ui;

import java.awt.BorderLayout;
import net.sf.maltcms.chromaui.msviewer.spi.MassSpectrumPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//net.sf.maltcms.chromaui.msviewer.api.ui//MassSpectrumViewer//EN",
autostore = false)
@TopComponent.Description(preferredID = "MassSpectrumViewerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "navigator", openAtStartup = false)
@ActionID(category = "Window", id = "net.sf.maltcms.chromaui.msviewer.api.ui.MassSpectrumViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MassSpectrumViewerAction",
preferredID = "MassSpectrumViewerTopComponent")
public final class MassSpectrumViewerTopComponent extends TopComponent {

    private MassSpectrumPanel msp = new MassSpectrumPanel();
    
    public MassSpectrumViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(MassSpectrumViewerTopComponent.class, "CTL_MassSpectrumViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(MassSpectrumViewerTopComponent.class, "HINT_MassSpectrumViewerTopComponent"));
        add(msp, BorderLayout.CENTER);
        setDisplayName("Mass Spectrum Viewer");// " + f.getDisplayName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        msp.componentOpened();
    }

    @Override
    public void componentClosed() {
        msp.componentClosed();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
