/* 
 * Maui, Maltcms User Interface. 
 * Copyright (C) 2008-2014, The authors of Maui. All rights reserved.
 *
 * Project website: http://maltcms.sf.net
 *
 * Maui may be used under the terms of either the
 *
 * GNU Lesser General Public License (LGPL)
 * http://www.gnu.org/licenses/lgpl.html
 *
 * or the
 *
 * Eclipse Public License (EPL)
 * http://www.eclipse.org/org/documents/epl-v10.php
 *
 * As a user/recipient of Maui, you may choose which license to receive the code 
 * under. Certain files or entire directories may not be covered by this 
 * dual license, but are subject to licenses compatible to both LGPL and EPL.
 * License exceptions are explicitly declared in all relevant files or in a 
 * LICENSE file in the relevant directories.
 *
 * Maui is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. Please consult the relevant license documentation
 * for details.
 */
package net.sf.maltcms.db.search.api.ui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import net.sf.maltcms.chromaui.project.api.types.DatabaseType;

/**
 * TODO link with project so that dbs are stored and retrieved.
 *
 * @author nilshoffmann
 */
public final class DatabaseCreatePanel extends javax.swing.JPanel {

	private DefaultComboBoxModel comboBoxModel;

	/**
	 * Creates new form DatabaseDefinitionPanel
	 */
	public DatabaseCreatePanel() {
		initComponents();
		comboBoxModel = new DefaultComboBoxModel(DatabaseType.values());
		jComboBox1.setModel(comboBoxModel);
		jComboBox1.setSelectedIndex(DatabaseType.USER.ordinal());
	}
	
	private DefaultComboBoxModel<Locale> getLocaleComboBoxModel() {
		Locale[] locales = Locale.getAvailableLocales();
		Arrays.sort(locales,new Comparator<Locale>() {

			@Override
			public int compare(Locale o1, Locale o2) {
				return o1.getDisplayName().compareTo(o2.getDisplayName());
			}
		});
		DefaultComboBoxModel<Locale> d = new DefaultComboBoxModel<Locale>(locales);
		return d;
	}
	
	public String getDatabaseDescriptorName() {
		return nameField.getText();
	}

	public List<Double> getMaskedMasses() {
		String text = maskedMasses.getText();
		if (text.isEmpty()) {
			return Collections.emptyList();
		}
		String[] values = text.split(",");
		List<Double> list = new ArrayList<Double>();
		for (String str : values) {
			list.add(Double.parseDouble(str));
		}
		return list;
	}

	public DatabaseType getDatabaseType() {
		return (DatabaseType) jComboBox1.getSelectedItem();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        localeComboBox = new javax.swing.JComboBox();
        localeComboBox.setRenderer(new LocaleCellRenderer());
        maskedMasses = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.jLabel4.text")); // NOI18N

        localeComboBox.setModel(getLocaleComboBoxModel());
        localeComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.localeComboBox.toolTipText")); // NOI18N
        localeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localeComboBoxActionPerformed(evt);
            }
        });

        maskedMasses.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.maskedMasses.text")); // NOI18N
        maskedMasses.setToolTipText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.maskedMasses.toolTipText")); // NOI18N
        maskedMasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskedMassesActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.jLabel6.text")); // NOI18N

        nameField.setText(org.openide.util.NbBundle.getMessage(DatabaseCreatePanel.class, "DatabaseCreatePanel.nameField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localeComboBox, 0, 267, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 267, Short.MAX_VALUE)
                    .addComponent(maskedMasses, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(nameField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(localeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maskedMasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	public Locale getSelectedLocale() {
		Locale locale = (Locale) localeComboBox.getSelectedItem();
		if (locale == null) {
			return Locale.getDefault();
		} else {
			return locale;
		}
	}

	private static final class LocaleCellRenderer extends DefaultListCellRenderer {

		public LocaleCellRenderer() {
			setOpaque(true);
		}

		@Override
		public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
			Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
			setText(((Locale)value).getDisplayName());
			return c;
		}
	}

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void localeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localeComboBoxActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_localeComboBoxActionPerformed

    private void maskedMassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskedMassesActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_maskedMassesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox localeComboBox;
    private javax.swing.JTextField maskedMasses;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
